# FIXME provide URL matching the destination environment
streamx.blueprints.external-references-rewriter.base-url-for-relative-paths=http://web.127.0.0.1.nip.io

streamx.blueprints.external-references-rewriter.processable-payload-types=data/product_with_images
streamx.blueprints.external-references-rewriter.json-external-resource-jsonpath-selectors=$..primaryImage.url
streamx.blueprints.external-references-rewriter.emitted-page-type=page/external
streamx.blueprints.external-references-rewriter.emitted-web-resource-type=web-resource/external
streamx.blueprints.external-references-rewriter.emitted-asset-type=asset/external