# disable authentication for local run
QUARKUS_HTTP_AUTH_PERMISSION_BEARER_POLICY=permit

streamx.proxy.config.subject-regex-rewrite.enabled=true

streamx.proxy.config.subject-regex-rewrite.types.pages.types=com.streamx.blueprints.page.published.v1,com.streamx.blueprints.page.unpublished.v1
streamx.proxy.config.subject-regex-rewrite.types.pages.patterns.config1.match-pattern=^/published/puresight/pages/(.*)
streamx.proxy.config.subject-regex-rewrite.types.pages.patterns.config1.rewrite-pattern=/$1

streamx.proxy.config.subject-regex-rewrite.types.assets.types=com.streamx.blueprints.asset.published.v1,com.streamx.blueprints.asset.unpublished.v1
streamx.proxy.config.subject-regex-rewrite.types.assets.patterns.config1.match-pattern=^/published/puresight/assets/(.*)
streamx.proxy.config.subject-regex-rewrite.types.assets.patterns.config1.rewrite-pattern=/assets/$1
