# FIXME provide URL matching the destination environment
streamx.blueprints.sitemap-generator.base-url=http://web.127.0.0.1.nip.io

streamx.blueprints.sitemap-generator.output-key=/sitemap.xml
streamx.blueprints.sitemap-generator.output-type=web-resource/sitemap