apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: cache-control-web-resources
  namespace: so-ds-gateway-e0b12
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: sx-mesh-streamx-gateway-web-server-route