# Redirects
map $request_uri $new_uri {
    default "";
    /home.html /;
    /images/mail/logo/logo.png /assets/mail/signature/logo.png;
    /images/mail/logo/greybar.png /assets/mail/signature/greybar.png;
}

server {
    listen       80;
    server_name  ds.pl;
    index        homepage.html;

    include conf.d/includes/ensure-https.conf;
    include conf.d/includes/compression.conf;

    # Apply redirects
    if ($new_uri != "") {
        rewrite ^(.*)$ $new_uri permanent;
    }

    # Remove duplicated slashes
    rewrite (.*)//(.*) $1/$2 permanent;

    # 404 error page
    error_page 404 /errors/404.html;
    location /errors {
        root    /usr/share/nginx/html/published/ds-website/pages/errors;
        internal;
    }

    location /robots.txt {
        root    /usr/share/nginx/html/published/ds-website;
        try_files $uri /assets/static/robots.txt/jcr:content/renditions/original.txt =404;
    }

    location /sitemap.xml {
        root    /usr/share/nginx/html/published/ds-website;
        try_files $uri /assets/static/sitemap.xml/jcr:content/renditions/original.xml =404;
    }

    location /favicon.ico {
        root    /usr/share/nginx/html/published/ds-website;
        try_files $uri /assets/static/favicon.ico/jcr:content/renditions/original.ico =404;
    }

    location /apps {
        root   /usr/share/nginx/html;
    }

    location /libs {
        root   /usr/share/nginx/html;
    }

    # HTML pages and root page
    location ~ (.html|/)$ {
        ssi  on;
        root   /usr/share/nginx/html/published/ds-website/pages;
    }

    # Assets with the original renditions support
    location ~ ^/assets/(.*)\.(.*)$ {
        root    /usr/share/nginx/html/published/ds-website;
        try_files $uri $uri/jcr:content/renditions/original.$2 =404;
    }

    location / {
        root   /usr/share/nginx/html/published/ds-website;
    }

}